version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    build: .
    command: ./entrypoints/docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
    volumes:
      - .:/Blog
      - gems:/gems
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    tty: true
    stdin_open: true


volumes:
  postgres:
  gems:
